### ISSUE TITLE
Web of Yose servers

### ISSUE THREAD

**Issue by lantoli** [yosethegame/yosethegame#9]
Hi, 
just a crazy idea but maybe it's hard to implement.

Yose main server only takes care of registration, scores, etc.

Worlds are tested by other servers. So when a level must be tried, Yose main server asks another server to run the test and get the result. (so you basically call another server with the player url server and level to play) and get ok/fail/error.

So people can implement new worlds in different languages (not just node) and main Yose server is not affected.

One server can test several worlds, one world can be tested by several servers. A server registration mechanism should be in place, maybe in the beginning it's just a property file which must be updated manually.

Less load problems, for instance every world can be tested by a heroku free app.

Don't know if it's worth the effort.

**Comment by codingthat** [comment]
@lantoli Did you get another server running?  I noticed the main yosethegame.com succumbed to Heroku's free-tier sunset.

**Comment by lantoli** [comment]
hey @codingthat , sorry i didn't, don't know if @ericminio continues with the project

**Comment by ericminio** [comment]
You guessed well. Yose did not survive the new price model.

**Comment by codingthat** [comment]
Any interest in finding a new host?  Maybe ElephantSQL + Glitch?  It apparently needs some npm/Node.js dependency updates though.

**Comment by ericminio** [comment]
Hi,
I have no plan to continue this project on a new future.
Feel free to though. It is what open source already means.
